---
- include: roles/qbroker/tasks/remove_item.yml
  vars:
    my_dir: "{{qbroker_dir}}"
  with_items:
    - "bin/{{qb_service}}.sh"
    - "flow/{{mbservice_service_id}}"
    - "jndi/{{mbservice_service_id}}"
    - "{{qb_service}}"
