---
- name: Template of Flow.json
  template:
    src: Flow.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/Flow.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    id: "{{qbroker_service_id}}"
    qb_dir: "{{qbroker_dir}}"
    log_dir: "{{tomcat_logdir}}"
  notify: Restart_tomcat.service

- name: Template of rpt_global_var.json.j2
  template:
    src: rpt_global_var.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/rpt_global_var.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    url: "{{mbservice_jndi_url}}"
    ctx: "{{mbservice_context_factory}}"
    user: "{{mbservice_mq_user}}"
    passwd: "{{mbservice_mq_passwd}}"
  notify: Restart_tomcat.service

- name: Template of bindings.j2
  template:
    src: "{{mbservice_mq}}.bindings.j2"
    dest: "{{qbroker_dir}}/jndi/{{qbroker_service_id}}/.bindings"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    host: "{{mbservice_broker_host}}"
    port: "{{mbservice_broker_port}}"
    out_q: "{{mbservice_out_queue}}"
    proxy_q: "{{mbservice_proxy_queue}}"
  notify: Restart_tomcat.service
